[package]
name = "rcli"
version = "0.1.0"
edition = "2021"
authors = ["lukki <nolan0707@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
